# docker-compose.yml
version: '3.8'

services:
  # Next.js Application Service
  nextjs-app:
    container_name: fitness-tracker-app
    image: nguyentuananh190403/authv4:stg
    restart: unless-stopped
    ports:
      # Expose port 3000 on the VPS to the outside world
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb
    env_file:
      # Tells Docker Compose to load variables from this file
      - ./.env.production

  # MongoDB Database Service
  mongodb:
    container_name: fitness-tracker-db
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local