# docker-compose.yml
services:
  # Next.js Application Service
  nextjs-app:
    container_name: ${CONTAINER_NAME:-fitness-tracker-app}
    image: ${IMAGE_NAME:-nguyentuananh190403/fitness-app:dev}
    restart: unless-stopped
    ports:
      # Map environment-specific ports
      - "${PORT:-3000}:3000"
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
    env_file:
      # Load environment-specific env file
      - ./.env.${ENVIRONMENT:-dev}

  # MongoDB Database Service
  mongodb:
    container_name: ${DB_CONTAINER_NAME:-fitness-tracker-db}
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local