# docker-compose.yaml

version: '3.8'

services:
  nextjs-app:
    container_name: fitness-tracker-app
    image: nguyentuananh190403/fitness-app:latest
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/fitness-tracker-by-jim
      - NEXTAUTH_URL=http://103.28.32.27:80
      - AUTH_URL=http://103.28.32.27:80
      - NEXTAUTH_SECRET=jimdeptraivai
      - AUTH_SECRET=jimdeptraivai
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: fitness-tracker-db
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local